source 'https://rubygems.org'
#ruby '2.0.0'

gem 'rails', '4.0.0'

group :production do
	gem 'pg'
	gem 'rails_12factor'
	gem 'simple_postmark'
end

group :development, :test do 
gem 'sqlite3'
end

gem 'acts_as_votable'
gem 'commontator', '~> 4.2.0'
gem 'sass-rails', '>= 3.2' # sass-rails needs to be higher than 3.2
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass'
gem 'devise', '~>3.1.0.rc2'
gem 'paperclip', '~> 3.0'
gem 'aws-sdk', '~> 1.20.0'
gem 'jquery-turbolinks'
gem 'masonry-rails', '~> 0.2.0'
gem 'will_paginate', '~> 3.0'
gem 'will_paginate-bootstrap'


group :doc do
  gem 'sdoc', require: false
end